import type { Metadata } from "next";
import "./globals.css";
import { HeroUiProvider } from "../Providers/HerouiProvider";
import Navbar from "@/components/modules/navbar/Navbar";
import { ThemeProvider } from "next-themes";
import { ShootingStars } from "@/components/modules/shootingStars/shooting-stars";
import localFont from "next/font/local";
import Sidebar from "@/components/modules/sidebar/Sidebar";

export const vazirmatn = localFont({
  src: [
    {
      path: "../fonts/vazir/Vazir-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../fonts/vazir/Vazir-Medium.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/vazir/Vazir-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-vazir",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body
        className={`${vazirmatn.variable} flex gap-4 px-4 bg-[#f5f0fe] text-black antialiased dark:bg-[#0a0a0a] dark:text-white`}
      >
        <ThemeProvider attribute="class">
          <Sidebar />
          <HeroUiProvider>
            <div className="bg-white w-full rounded-lg mt-3" style={{boxShadow:'0px -1px 9px -5px rgba(0,0,0,0.75)'}}>
              <Navbar />
              <div className={`relative z-50 font-vazir`} >{children}</div>
            </div>
          </HeroUiProvider>
          {/* <ShootingStars /> */}
        </ThemeProvider>
      </body>
    </html>
  );
}
