import type { Metadata } from "next";
import "./globals.css";
import { HeroUiProvider } from "../Providers/HerouiProvider"; 
import { ThemeProvider } from "next-themes";
import { ShootingStars } from "@/components/modules/shootingStars/shooting-stars";
import localFont from "next/font/local";
import Sidebar from "@/components/modules/sidebar/Sidebar";

export const vazirmatn = localFont({
  src: [
    {
      path: "../fonts/vazir/Vazir-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../fonts/vazir/Vazir-Medium.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/vazir/Vazir-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-vazir",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body
        className={`${vazirmatn.variable} flex md:gap-4 bg-[#f5f0fe] md:px-4 sm:pl-4 text-black antialiased dark:bg-[#0a0a0a] dark:text-white`}
      >
        <ThemeProvider attribute="class">
          <Sidebar />
          <HeroUiProvider>{children}</HeroUiProvider>
          {/* <ShootingStars /> */}
        </ThemeProvider>
      </body>
    </html>
  );
}
